# 81fae51afba4f064fdddc1cdaa8f0935ac32c46f
# ac42f815718f4e1bd0682d3acf12d8152e0fd25e
# 714fd47409ee3e443ab96c810b9c53fb21a7734b
# 6f20ad77a50506cc4e1e5945bc7aa30c0476b88c
# https://github.com/settings/tokens/256155318
image: Visual Studio 2015
branches:
  only:
    - source
    
environment:
  access_token:
    secure: lWYrWR0tY3rp4Ic1SNRSrX+F2g/+in4+DxSvAbn5Nh9xeJqPvCimjxBEAJ0rM4j/

install:
  - C:\Python37\python -m pip install -U pip
  - C:\Python37\python -m pip install -U pelican markdown
  - git submodule status
  - git submodule init
  - git submodule status
  - git submodule update --remote
  - git submodule status
  # - cinst pretzel

before_build:


build_script:
  # - ps: .\pretzel.ps1
  - cmd: C:\Python37\Scripts\pelican content

build: true

test: off

on_success:
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  - git config --global user.email %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
  - git config --global user.email
  - git config --global user.name %APPVEYOR_REPO_COMMIT_AUTHOR%
  - git config --global user.name
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - ps: type "$env:USERPROFILE\.git-credentials"
  - cmd: cd output
  - cmd: pwd
  - git add .
  - git commit -m "From Appveyor [skip appveyor]"
  - git push origin HEAD:master -f
